version: '3.1'

services:
  movie:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
       DB_USER: root
       DB_PW: mysql@2021
       DB_PORT: 3306
       DB_URL: mysql
       DB_NAME: movie
    restart: always
    networks:
      - movie-net
  mysql:
    container_name: mysql-db
    image: mysql:5.7.35
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql@2021
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql@2021
    command: --init-file /data/application/init.sql
    networks:
      - movie-net
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql
networks:
  movie-net:
volumes:
  mysql-data: